In [39]:
import numpy as np
import pandas as pd

In [2]:
#default type is float
#np.full() will fill infinite
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
list = np.arange(8)
list

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
list.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
list2 = np.array([67,43,100])
print(list2)
sorted = np.sort(list2, kind='merge sort')
print(sorted)

[ 67  43 100]
[ 43  67 100]


In [17]:
#list reversing
list2[::-1].sort()
print(list2)

[100  67  43]


In [27]:
#sort and search the list
search_sort = np.array([56,45,89,30,12,78])
searched_ele = np.searchsorted(search_sort, 56)
print(searched_ele)

5


In [32]:
#provides index where it can index
np.searchsorted([10,12,14,15], 14, side='left')

2

In [35]:
#indexing slicing
array = np.array([4,5,7,9,3,15,12,17])
array[1:6:2]

array([ 5,  9, 15])

In [38]:
array2 = np.arange(8)
print(array2)
array2[slice(1,6,2)]

[0 1 2 3 4 5 6 7]


array([1, 3, 5])

In [40]:
#PANDAS
arr = np.array([10,20])
series = pd.Series(arr)
series

0    10
1    20
dtype: int64

In [41]:
series.describe()

count     2.000000
mean     15.000000
std       7.071068
min      10.000000
25%      12.500000
50%      15.000000
75%      17.500000
max      20.000000
dtype: float64

In [44]:
series2 = pd.Series([40,50])
series.append(series2, ignore_index=True)

0    10
1    20
2    40
3    50
dtype: int64

In [45]:
series2.apply(lambda x: x**2)

0    1600
1    2500
dtype: int64

In [47]:
dict = {'col1': [10,20], 'col2': [30, np.nan]}
df = pd.DataFrame(data=dict)
print(df)

   col1  col2
0    10  30.0
1    20   NaN


In [48]:
df.describe()

col1  col2
count   2.000000   1.0
mean   15.000000  30.0
std     7.071068   NaN
min    10.000000  30.0
25%    12.500000  30.0
50%    15.000000  30.0
75%    17.500000  30.0
max    20.000000  30.0

In [49]:
df.count()

col1    2
col2    1
dtype: int64

In [50]:
data = pd.read_csv("Automobile.csv")
data.head()

symboling  normalized_losses         make fuel_type aspiration  \
0          3                168  alfa-romero       gas        std   
1          3                168  alfa-romero       gas        std   
2          1                168  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0             two  convertible          rwd           front        88.6  ...   
1             two  convertible          rwd           front        88.6  ...   
2             two    hatchback          rwd           front        94.5  ...   
3            four        sedan          fwd           front        99.8  ...   
4            four        sedan          4wd           front        99.4  ...   

   engine_size  fuel_system  bore  stroke compression_ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0        111   
1          130         mpfi  3.47    2.68               9.0        111   
2          152         mpfi  2.68    3.47               9.0        154   
3          109         mpfi  3.19    3.40              10.0        102   
4          136         mpfi  3.19    3.40               8.0        115   

   peak_rpm city_mpg  highway_mpg  price  
0      5000       21           27  13495  
1      5000       21           27  16500  
2      5000       19           26  16500  
3      5500       24           30  13950  
4      5500       18           22  17450  

[5 rows x 26 columns]

In [52]:
grouped = data.groupby("body_style")
grouped.first()

symboling  normalized_losses           make fuel_type aspiration  \
body_style                                                                      
convertible          3                168    alfa-romero       gas        std   
hardtop              0                 93  mercedes-benz    diesel      turbo   
hatchback            1                168    alfa-romero       gas        std   
sedan                2                164           audi       gas        std   
wagon                1                168           audi       gas        std   

            number_of_doors drive_wheels engine_location  wheel_base  length  \
body_style                                                                     
convertible             two          rwd           front        88.6   168.8   
hardtop                 two          rwd           front       106.7   187.5   
hatchback               two          rwd           front        94.5   171.2   
sedan                  four          fwd           front        99.8   176.6   
wagon                  four          fwd           front       105.8   192.7   

             ...  engine_size  fuel_system  bore stroke compression_ratio  \
body_style   ...                                                            
convertible  ...          130         mpfi  3.47   2.68               9.0   
hardtop      ...          183          idi  3.58   3.64              21.5   
hatchback    ...          152         mpfi  2.68   3.47               9.0   
sedan        ...          109         mpfi  3.19   3.40              10.0   
wagon        ...          136         mpfi  3.19   3.40               8.5   

             horsepower peak_rpm  city_mpg  highway_mpg  price  
body_style                                                      
convertible         111     5000        21           27  13495  
hardtop             123     4350        22           25  28176  
hatchback           154     5000        19           26  16500  
sedan               102     5500        24           30  13950  
wagon               110     5500        19           25  18920  

[5 rows x 25 columns]

In [54]:
data.loc['diesel']

KeyError: 'diesel'

In [ ]:
#used to serialise and save it as binary
import pickle
df.to_pickle("abcd.csv")
pd.read_pickle("abcd.csv")